[package]
name = "jql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r3bl_rs_utils = "*"
atty = "*"
serde_json = "1.0"
colored_json = "2"